# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80e62bd551f8ad042651476158199e486dcec287d66d2c078c7170cf117b4c64d6e648d478d8f6dd41d8c4ef5e160c8f4aa2b38d39e4c75be0f00e1dc2fa0b27

test:
  secret_key_base: 5f4184e36add77d8d4446438a0e46ade6c0bc66642c22f303415be73b7f95cfb14228e7767d2b29042da398d4b87b5d7fd4101f554ca54f72c123dc1883a197e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
